### ISSUE TITLE
error: failed to select a version for `libsqlite3-sys`

### ISSUE THREAD

**Issue by Zerounary** [rust-db/refinery#246]
use `rusqlite` feature with this error 

![image](https://user-images.githubusercontent.com/31512287/189508783-9006882b-c14a-4352-b490-bbc51aa63d43.png)

How to fix it ?    : )

**Comment by jxs** [comment]
Hi, it seems you have a dependency that depends on an earlier `rusqlite` version. Can you show your `Cargo.toml` ?

**Comment by goern** [comment]
I see the same error
```
...
[dependencies]
devise_core = "0.3.1"
juniper = "0.15.10"
juniper_rocket = "0.8.2"
libsqlite3-sys = "0.25.1"
log = "0.4.17"
pear_codegen = "0.2.3"
refinery = {version = "0.8.6", features = ["rusqlite"]}
rocket = {version = "0.5.0-rc.2", features = ["secrets"]}
rocket_http = "0.5.0-rc.2"
rusqlite = "0.28.0"
stderrlog = "0.5.3"
...
```

**Comment by Zerounary** [comment]
This is my `Cargo.toml` 
```toml
[dependencies]
rbs = "0.1.11"
rbatis = "4.0.39"
rbdc-pg = "0.1.16"
rbdc-mysql = "0.1.16"
rbdc-sqlite = "0.1.13"
refinery = { version = "0.8.6", features = ["mysql", "tokio-postgres", "rusqlite"]}
tokio-postgres = "0.7.7"
mysql = "22.2.0"
```

The conflict exists between `refinery` and `rbdc-sqlite` .
