### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by akhilles** [rust-db/refinery#54]
The `README.md` implies that the project is licensed only under MIT:

> ## License
> 
> This project is licensed under the [MIT license](LICENSE).

But the `Cargo.toml` manifests suggest it's dual licensed under MIT or Apache-2.0:

```toml
[package]
name = "refinery"
version = "0.2.0"
authors = ["Katharina Fey <kookie@spacekookie.de>", "João Oliveira <hello@jxs.pt>"]
license = "MIT OR Apache-2.0"
```

I think this should be clarified. If dual license was the intent, I'd follow the recommendations at https://rust-lang.github.io/api-guidelines/necessities.html#crate-and-its-dependencies-have-a-permissive-license-c-permissive
